# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-11 11:53
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('output', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.IntegerField()),
                ('poly', django.contrib.gis.db.models.fields.PolygonField(default='', srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_point', django.contrib.gis.db.models.fields.PointField(default='', srid=4326)),
                ('area', models.IntegerField()),
                ('income', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adhaar_id', models.IntegerField()),
                ('name', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Property_farm',
            fields=[
                ('farm_id', models.AutoField(primary_key=True, serialize=False)),
                ('a_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Identity')),
            ],
        ),
        migrations.CreateModel(
            name='Property_house',
            fields=[
                ('house_id', models.AutoField(primary_key=True, serialize=False)),
                ('a_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Identity')),
            ],
        ),
        migrations.CreateModel(
            name='Well',
            fields=[
                ('w_id', models.AutoField(primary_key=True, serialize=False)),
                ('w_point', django.contrib.gis.db.models.fields.PointField(default='', srid=4326)),
                ('depth', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='house',
            name='h_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Property_house'),
        ),
        migrations.AddField(
            model_name='farm',
            name='f_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Property_farm'),
        ),
        migrations.AddField(
            model_name='crop',
            name='c_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Farm'),
        ),
    ]
