# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='img',
            field=models.CharField(default='', max_length=500),
        ),
    ]
